// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3kTFEZGhj1jCSZJICliw0hgAmVfN9z20',
    appId: '1:891939444570:web:b67e710568bf9a15c6c563',
    messagingSenderId: '891939444570',
    projectId: 'setsi-sa-mbaar',
    authDomain: 'setsi-sa-mbaar.firebaseapp.com',
    storageBucket: 'setsi-sa-mbaar.firebasestorage.app',
    measurementId: 'G-G655YPTF1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI8zUUVyVyAvaW8RSL4vzzdfm-OrcVa-E',
    appId: '1:891939444570:android:c24abe785b7aea59c6c563',
    messagingSenderId: '891939444570',
    projectId: 'setsi-sa-mbaar',
    storageBucket: 'setsi-sa-mbaar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLU9yrm2risxQSto90mdI1pA2ATnSKQjU',
    appId: '1:891939444570:ios:3742879b5cf4a1e1c6c563',
    messagingSenderId: '891939444570',
    projectId: 'setsi-sa-mbaar',
    storageBucket: 'setsi-sa-mbaar.firebasestorage.app',
    iosBundleId: 'com.example.setsiSaMbaar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLU9yrm2risxQSto90mdI1pA2ATnSKQjU',
    appId: '1:891939444570:ios:3742879b5cf4a1e1c6c563',
    messagingSenderId: '891939444570',
    projectId: 'setsi-sa-mbaar',
    storageBucket: 'setsi-sa-mbaar.firebasestorage.app',
    iosBundleId: 'com.example.setsiSaMbaar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3kTFEZGhj1jCSZJICliw0hgAmVfN9z20',
    appId: '1:891939444570:web:571dad1b997029d7c6c563',
    messagingSenderId: '891939444570',
    projectId: 'setsi-sa-mbaar',
    authDomain: 'setsi-sa-mbaar.firebaseapp.com',
    storageBucket: 'setsi-sa-mbaar.firebasestorage.app',
    measurementId: 'G-6TH6D8PWP3',
  );
}
